version: "3"
services:
  api:
    image: ghcr.io/ada-social-network/api:latest
    volumes:
      - data-volume:/usr/local/ada/data
    ports:
      - "8080:8080"

  front:
    build: "."
    ports: 
      - "3001:3000"
    


volumes:
  data-volume:

