version: "3"
services:
  api:
    image: ghcr.io/ada-social-network/api:latest
    volumes:
      - data-volume:/usr/local/ada/data
    ports:
      - "8080:8080"

  front:
    image: ghcr.io/ada-social-network/front:latest
    ports:
      - "8081:80"

volumes:
  data-volume:

